### PR TITLE
[env] fix memory leak & enable vLLM v1

### LINKED ISSUE #50: memory usage growing
When I train geometry3k using run_qwen2_5_vl_7b_geo. I encountered an issue where memory usage is growing slowly. I guess there is a memory leakage.

### PR DESCRIPTION
**Pull request by hiyouga**
Fixes: #50 https://github.com/volcengine/verl/issues/429

Use the docker image to avoid OOM or execute

```bash
export VLLM_COMMIT=227578480d71fc94ef46ca77fb69496412158d68
sudo pip install vllm --pre --extra-index-url https://wheels.vllm.ai/${VLLM_COMMIT}
git clone -b verl_v1 https://github.com/hiyouga/vllm.git
sudo cp -r vllm/vllm/ /usr/local/lib/python3.10/dist-packages/
```

### CODE REVIEW

File: examples/run_qwen2_5_vl_7b_geo.sh [hunk 1]
```diff
@@ -1,6 +1,7 @@
 set -x
 
 export VLLM_ATTENTION_BACKEND=XFORMERS
+export VLLM_USE_V1=0
```
Comment (wzq016) [inline examples/run_qwen2_5_vl_7b_geo.sh:4]: Shouldn't this be `VLLM_USE_V1=0` to enable V1?

Comment (NIL-zhuang) [reply examples/run_qwen2_5_vl_7b_geo.sh:4]: VLLM_COMMIT=227578480 fixes memory leak in V0 Engine. 
You can just use V1 Engine following https://verl.readthedocs.io/en/latest/README_vllm0.7.html#use-vllm-v1-engine

Comment (wzq016) [reply examples/run_qwen2_5_vl_7b_geo.sh:4]: Oh, I see; so, the bash files do not hope users enable the V1 engine because they may not properly set data_parallel_size there?

Comment (hiyouga) [reply examples/run_qwen2_5_vl_7b_geo.sh:4]: You can enable vllm v1 using https://hub.docker.com/layers/hiyouga/verl/ngc-th2.5.1-cu120-vllm0.7.4-hotfix/images/sha256-864124d32147f5e9b31916656b441f19d77c1c03e3448c8504b0025df59121b2

Comment (wzq016) [reply examples/run_qwen2_5_vl_7b_geo.sh:4]: thanks for the reply!
